//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project113_G3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQ_Reported
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RQ_Reported()
        {
            this.UserDatas = new HashSet<UserData>();
        }
    
        public int RQrp_Id { get; set; }
        public string RQrp_ByUsername { get; set; }
        public string RQrp_ToUserName { get; set; }
        public string RQrp_Toppic { get; set; }
        public Nullable<System.DateTime> RQrp_Date { get; set; }
        public string RQrp_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserData> UserDatas { get; set; }
    }
}
